# Generated by Django 3.0.2 on 2020-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapplication', '0004_auto_20200307_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
