# Generated by Django 4.0.4 on 2022-05-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapplication', '0005_auto_20200309_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('data_id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'UserImportData',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_id',
            field=models.IntegerField(),
        ),
    ]
